### ISSUE TITLE
Rolar para final da lista de mensagens

### ISSUE THREAD

**Issue by Dhayvison** [Dhayvison/dutch-blitz-online-front#1]
O comportamento atual da listagem de mensagem oculta as mensagens que excedem o tamanho vertical da lista. O ideal é que a visualização fosse adaptada para visualizar primeiro as mensagens que chegam no chat.

https://stackoverflow.com/questions/37620694/how-to-scroll-to-bottom-in-react

**Comment by Dhayvison** [comment]
https://pt-br.reactjs.org/docs/refs-and-the-dom.html

**Comment by Dhayvison** [comment]
Adicionar adorno às mensagens do chat.
```css
.timeline-comment--caret::after, .timeline-comment--caret::before {
    position: absolute;
    top: 11px;
    right: 100%;
    left: -8px;
    display: block;
    width: 8px;
    height: 16px;
    pointer-events: none;
    content: " ";
    -webkit-clip-path: polygon(0 50%, 100% 0, 100% 100%);
    clip-path: polygon(0 50%, 100% 0, 100% 100%);
}

```

![image](https://user-images.githubusercontent.com/34067572/171038224-568c1590-6ba2-4f73-88e2-16cd7c4e8c2a.png)
